---
# https://wiki.archlinux.org/title/tor#Pacman
- name: pkg-manager > configuring for Arch
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: ^XferCommand =
    insertafter: '^\[options\]$'
    line: 'XferCommand = /usr/bin/curl --socks5-hostname {{ tor_localhost }}:{{ tor_package_manager_port }} --location --continue-at - --fail --output %o %u'
    state: present
  when: ansible_distribution == 'Archlinux'

- name: pkg-manager > ensure xbps.d exist on Void
  ansible.builtin.file:
    path: /etc/xbps.d
    state: directory
  when: ansible_distribution == 'Void'

- name: pkg-manager > copying repo file
  ansible.builtin.file:
    src: /usr/share/xbps.d/00-repository-main.conf
    dest: /etc/xbps.d/00-repository-main.conf
    state: hard
  when: ansible_distribution == 'Void'

# https://docs.voidlinux.org/xbps/repositories/mirrors/tor.html#using-tor-mirrors
- name: pkg-manager > change repo address
  ansible.builtin.replace:
    path: /etc/xbps.d/00-repository-main.conf
    regexp: 'https://repo-default.voidlinux.org'
    replace: '{{ tor_package_manager_onion }}'
  when: ansible_distribution == 'Void' and tor_package_manager_onion is defined

- name: pkg-manager > need to set socks_proxy
  ansible.builtin.lineinfile:
    path: /etc/profile
    regexp: ^export SOCKS_PROXY=
    insertafter: '^umask*'
    line: 'export SOCKS_PROXY="{{ tor_localhost }}:{{ tor_package_manager_port }}"'
    state: present
  when: ansible_distribution == 'Void'

- name: pkg-manager > checking sudo...
  ansible.builtin.stat:
    path: /etc/sudoers.d
  register: p

- name: pkg-manager > add sudo permission
  ansible.builtin.copy:
    dest: /etc/sudoers.d/tor
    content: 'Defaults env_keep += "SOCKS_PROXY"'
    mode: 0644
  when: ansible_distribution == 'Void' and p.stat.exists
