---
- name: tor > gentoo use flags...
  ansible.builtin.template:
    src: package-use.j2
    dest: /etc/portage/package.use/tor
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == 'Gentoo'

- name: tor > installing dependencies...
  ansible.builtin.package:
    name:
      - tor
      - torsocks
    state: present

- name: tor > ensure config directory {{ tor_config_dir }} exist
  ansible.builtin.file:
    path: '{{ tor_config_dir }}'
    state: directory

- name: tor > installing socksport template in {{ tor_config_dir }}...
  ansible.builtin.template:
    src: socksport.j2
    dest: '{{ tor_config_dir }}/socksport.conf'
    owner: root
    group: root
    mode: 0644
  notify: restart tor

- name: tor > configuring /etc/tor/torrc...
  ansible.builtin.lineinfile:
    path: /etc/tor/torrc
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^\%include'
      line: '%include {{ tor_config_dir }}/*.conf'
    - regexp: ^ConnectionPadding
      line: ConnectionPadding 1
    - regexp: ^Sandbox
      line: Sandbox 1
  notify: restart tor

- name: tor > configuring torsocks...
  ansible.builtin.lineinfile:
    path: /etc/tor/torsocks.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - regexp: '^TorAddress'
      line: 'TorAddress {{ tor_localhost }}'
    - regexp: '^TorPort'
      line: 'TorPort {{ tor_stream_port_default }}'
    - regexp: '^IsolatePID'
      line: 'IsolatePID 1'

- name: tor > enabling service
  ansible.builtin.service:
    name: tor
    enabled: true
    state: started

