---
# defaults file for os
os_hostname: false
os_hostname_value: 'host'
os_hostname_list: []

# Spoofing mac
os_mac_change: false

os_machine_id: false

# a 32 hexa lowercase character
os_machine_id_value: 'b08dfa6083e7567a1921a715000001fb'

############################
# Timezone
os_timezone: false
os_timezone_value: 'UTC'
